### ISSUE TITLE
Issue when punctuation found at the end of a chunk

### ISSUE THREAD

**Issue by jeffrey-hughes** [StatCan/Canonym#1]
Hi, I've been testing out the Canonym package with our data, and I ran into an error: `IndexError: list index out of range`

It occurred when processing a long text string, which causes the transformer recognizer to split the text into chunks. The chunking code, as far as I can tell, tries to split text at the end of a sentence when possible. By chance, one of the chunks ended with punctuation already -- the last token was a "." character. The code then causes an issue at this line: https://github.com/StatCan/Canonym/blob/main/src/canonym/recognizers/transformer_recognizers.py#L153

Basically, the use of a negative index will typically count items starting from the end of the list, but in this case it ended up trying to split at `tokens[:-0], tokens[-0:]`, which does the opposite of what it should (it puts all the tokens in the "overflow", rather than including all the tokens in the chunk). It's one of the drawbacks of using this sort of negative index.

The code ultimately hits an error here when it tries to index into an empty list: https://github.com/StatCan/Canonym/blob/main/src/canonym/recognizers/transformer_recognizers.py#L134

As far as I can tell, the `i == 0` is really just a special case, as the negative index should work for all other values, so I think you just need a special `if` statement to capture it:

```
if i == 0:
    return tokens, []
else:
    return tokens[:-i], tokens[-i:]
```

I'm happy to submit a pull request to make this change, if that's easier.

Otherwise, I haven't run into any issues testing the package yet -- thanks for putting together such a useful package!

Jeff Hughes, ESDC

**Comment by alexandre-ist** [comment]
Thank you for raising this up and providing a solution, it was implemented and should solve the issue.
