### ISSUE TITLE
Issue with max_model_input_sizes attribute

### ISSUE THREAD

**Issue by shannonhlo** [StatCan/Canonym#3]
Hi, I came across the following error when trying to do maintenance on an old pipeline that uses the Canonym package:

> File "C:\Users\lshanno\AppData\Roaming\Python\Python310\site-packages\canonym\recognizers\transformer_recognizers.py", line 64, in load
>     self.max_model_input = list(self.tokenizer.max_model_input_sizes.values())[0]
> AttributeError: 'MobileBertTokenizerFast' object has no attribute 'max_model_input_sizes'

Based on the discussion in https://github.com/invoke-ai/InvokeAI/issues/6445, I changed https://github.com/StatCan/Canonym/blob/8c02c45f62cdce90c0af121350826572cfede68f/src/canonym/recognizers/transformer_recognizers.py#L64 to `self.max_model_input = self.tokenizer.model_max_length`. But another error occurs:

> Traceback (most recent call last):
  File "\\stpcflr-sasfs50\HLTH\CCMED\SpecialProjects\Anonymization\repo\deident\src\confusion.py", line 9, in <module>
    anonymizer = Canonym(ner_config_file = './ner_tag_config.yaml',
  File "C:\Users\lshanno\AppData\Roaming\Python\Python310\site-packages\canonym\canonym.py", line 43, in __init__
    self.language_detector=LanguageDetectorBuilder.from_iso_codes_639_1(*[IsoCode639_1[code.upper()] for code in self.ner_tagger.AVAILABLE_LANGS]).build()
  File "C:\Users\lshanno\AppData\Roaming\Python\Python310\site-packages\canonym\canonym.py", line 43, in <listcomp>
    self.language_detector=LanguageDetectorBuilder.from_iso_codes_639_1(*[IsoCode639_1[code.upper()] for code in self.ner_tagger.AVAILABLE_LANGS]).build()
TypeError: 'type' object is not subscriptable

~~I'm unsure if this TypeError is related to this package or is a bug in the pipeline, but it is included for the sake of thoroughness.~~

A TypeError is also produced when running this sample code snippet:
```
from canonym import Canonym

anonymizer = Canonym()

text = "This is John Doe, from Ottawa, his phone numer is 123-456-7890"
results = anonymizer.anonymize(text)
```

The error message:
> 	"name": "TypeError",
> 	"message": "'type' object is not subscriptable",
> 	"stack": "---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> Cell In[3], line 3
>       1 from canonym import Canonym
> ----> 3 anonymizer = Canonym()
>       5 text = \"This is John Doe, from Ottawa, his phone numer is 123-456-7890\"
>       6 results = anonymizer.anonymize(text)
> 
> File ~\\AppData\\Roaming\\Python\\Python310\\site-packages\\canonym\\canonym.py:43, in Canonym.__init__(self, ner_config_file, anonymizer_config_file)
>      35 self.tag_anonymizer = TagAnonymizer(config_file=anonymizer_config_file, supported_entities=self.supported_entities)
>      36 self.ACTIONS_DICT = {
>      37     'str': self.anonymize_text,
>      38     'TextItem': self.anonymize_text,
>    (...)
>      41     'Series': self.anonymize_pd_series
>      42 }
> ---> 43 self.language_detector=LanguageDetectorBuilder.from_iso_codes_639_1(*[IsoCode639_1[code.upper()] for code in self.ner_tagger.AVAILABLE_LANGS]).build()
> 
> File ~\\AppData\\Roaming\\Python\\Python310\\site-packages\\canonym\\canonym.py:43, in <listcomp>(.0)
>      35 self.tag_anonymizer = TagAnonymizer(config_file=anonymizer_config_file, supported_entities=self.supported_entities)
>      36 self.ACTIONS_DICT = {
>      37     'str': self.anonymize_text,
>      38     'TextItem': self.anonymize_text,
>    (...)
>      41     'Series': self.anonymize_pd_series
>      42 }
> ---> 43 self.language_detector=LanguageDetectorBuilder.from_iso_codes_639_1(*[IsoCode639_1[code.upper()] for code in self.ner_tagger.AVAILABLE_LANGS]).build()
> 
> TypeError: 'type' object is not subscriptable"

**Comment by alexandre-ist** [comment]
Issue should be fixed now. A clean install on a new Conda environment with Python 3.10 will be necessary.
